apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  template:
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue


